ERROR - 2025-05-01 16:31:48 --> Error connecting to the database: mysqli_sql_exception: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\user\Desktop\DevOps_Project\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\Users\user\Desktop\DevOps_Project\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'devops_tp', 3306, '', 0)
#1 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\user\Desktop\DevOps_Project\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\user\Desktop\DevOps_Project\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\user\Desktop\DevOps_Project\tests\ArticleModelTest.php(10): CodeIgniter\BaseModel->findAll()
#7 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\ArticleModelTest->testFindAllArticles()
#8 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#9 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\ArticleModelTest))
#11 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#13 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#14 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#15 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#16 C:\Users\user\Desktop\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\user\\D...')
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\user\Desktop\DevOps_Project\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\user\Desktop\DevOps_Project\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\user\Desktop\DevOps_Project\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\user\Desktop\DevOps_Project\tests\ArticleModelTest.php(10): CodeIgniter\BaseModel->findAll()
#6 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\ArticleModelTest->testFindAllArticles()
#7 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#8 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#9 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\ArticleModelTest))
#10 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#11 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#12 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#13 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#14 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#15 C:\Users\user\Desktop\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\user\\D...')
#16 {main}
ERROR - 2025-05-01 16:31:56 --> Error connecting to the database: mysqli_sql_exception: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\user\Desktop\DevOps_Project\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\Users\user\Desktop\DevOps_Project\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'devops_tp', 3306, '', 0)
#1 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\Users\user\Desktop\DevOps_Project\system\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\user\Desktop\DevOps_Project\system\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('STY123', 'article.ref', Array)
#6 C:\Users\user\Desktop\DevOps_Project\system\Validation\Validation.php(337): CodeIgniter\Validation\StrictRules\Rules->is_unique('STY123', 'article.ref', Array, NULL, 'ref')
#7 C:\Users\user\Desktop\DevOps_Project\system\Validation\Validation.php(202): CodeIgniter\Validation\Validation->processRules('ref', 'ref', 'STY123', Array, Array, 'ref')
#8 C:\Users\user\Desktop\DevOps_Project\system\BaseModel.php(1576): CodeIgniter\Validation\Validation->run(Array, NULL, NULL)
#9 C:\Users\user\Desktop\DevOps_Project\system\BaseModel.php(808): CodeIgniter\BaseModel->validate(Array)
#10 C:\Users\user\Desktop\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#11 C:\Users\user\Desktop\DevOps_Project\tests\ArticleModelTest.php(24): CodeIgniter\Model->insert(Array)
#12 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\ArticleModelTest->testCanCreateArticle()
#13 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#14 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#15 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\ArticleModelTest))
#16 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#17 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#18 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#19 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#20 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#21 C:\Users\user\Desktop\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\user\\D...')
#22 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\user\Desktop\DevOps_Project\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\Users\user\Desktop\DevOps_Project\system\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\user\Desktop\DevOps_Project\system\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('STY123', 'article.ref', Array)
#5 C:\Users\user\Desktop\DevOps_Project\system\Validation\Validation.php(337): CodeIgniter\Validation\StrictRules\Rules->is_unique('STY123', 'article.ref', Array, NULL, 'ref')
#6 C:\Users\user\Desktop\DevOps_Project\system\Validation\Validation.php(202): CodeIgniter\Validation\Validation->processRules('ref', 'ref', 'STY123', Array, Array, 'ref')
#7 C:\Users\user\Desktop\DevOps_Project\system\BaseModel.php(1576): CodeIgniter\Validation\Validation->run(Array, NULL, NULL)
#8 C:\Users\user\Desktop\DevOps_Project\system\BaseModel.php(808): CodeIgniter\BaseModel->validate(Array)
#9 C:\Users\user\Desktop\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#10 C:\Users\user\Desktop\DevOps_Project\tests\ArticleModelTest.php(24): CodeIgniter\Model->insert(Array)
#11 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\ArticleModelTest->testCanCreateArticle()
#12 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#13 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#14 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\ArticleModelTest))
#15 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#16 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#17 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#18 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#19 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#20 C:\Users\user\Desktop\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\user\\D...')
#21 {main}
ERROR - 2025-05-01 16:32:01 --> Error connecting to the database: mysqli_sql_exception: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\user\Desktop\DevOps_Project\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\Users\user\Desktop\DevOps_Project\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'devops_tp', 3306, '', 0)
#1 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\Users\user\Desktop\DevOps_Project\system\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\user\Desktop\DevOps_Project\system\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('DUPL001', 'article.ref', Array)
#6 C:\Users\user\Desktop\DevOps_Project\system\Validation\Validation.php(337): CodeIgniter\Validation\StrictRules\Rules->is_unique('DUPL001', 'article.ref', Array, NULL, 'ref')
#7 C:\Users\user\Desktop\DevOps_Project\system\Validation\Validation.php(202): CodeIgniter\Validation\Validation->processRules('ref', 'ref', 'DUPL001', Array, Array, 'ref')
#8 C:\Users\user\Desktop\DevOps_Project\system\BaseModel.php(1576): CodeIgniter\Validation\Validation->run(Array, NULL, NULL)
#9 C:\Users\user\Desktop\DevOps_Project\system\BaseModel.php(808): CodeIgniter\BaseModel->validate(Array)
#10 C:\Users\user\Desktop\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#11 C:\Users\user\Desktop\DevOps_Project\tests\ArticleModelTest.php(33): CodeIgniter\Model->insert(Array)
#12 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\ArticleModelTest->testDuplicateRefIsRejected()
#13 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#14 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#15 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\ArticleModelTest))
#16 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#17 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#18 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#19 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#20 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#21 C:\Users\user\Desktop\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\user\\D...')
#22 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\user\Desktop\DevOps_Project\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\Users\user\Desktop\DevOps_Project\system\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\user\Desktop\DevOps_Project\system\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('DUPL001', 'article.ref', Array)
#5 C:\Users\user\Desktop\DevOps_Project\system\Validation\Validation.php(337): CodeIgniter\Validation\StrictRules\Rules->is_unique('DUPL001', 'article.ref', Array, NULL, 'ref')
#6 C:\Users\user\Desktop\DevOps_Project\system\Validation\Validation.php(202): CodeIgniter\Validation\Validation->processRules('ref', 'ref', 'DUPL001', Array, Array, 'ref')
#7 C:\Users\user\Desktop\DevOps_Project\system\BaseModel.php(1576): CodeIgniter\Validation\Validation->run(Array, NULL, NULL)
#8 C:\Users\user\Desktop\DevOps_Project\system\BaseModel.php(808): CodeIgniter\BaseModel->validate(Array)
#9 C:\Users\user\Desktop\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#10 C:\Users\user\Desktop\DevOps_Project\tests\ArticleModelTest.php(33): CodeIgniter\Model->insert(Array)
#11 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\ArticleModelTest->testDuplicateRefIsRejected()
#12 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#13 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#14 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\ArticleModelTest))
#15 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#16 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#17 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#18 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#19 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#20 C:\Users\user\Desktop\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\user\\D...')
#21 {main}
ERROR - 2025-05-01 16:32:05 --> Error connecting to the database: mysqli_sql_exception: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\user\Desktop\DevOps_Project\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\Users\user\Desktop\DevOps_Project\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'devops_tp', 3306, '', 0)
#1 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\user\Desktop\DevOps_Project\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\user\Desktop\DevOps_Project\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\user\Desktop\DevOps_Project\tests\UserModelTest.php(10): CodeIgniter\BaseModel->findAll()
#7 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testFindAllUsers()
#8 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#9 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#11 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#13 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#14 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#15 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#16 C:\Users\user\Desktop\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\user\\D...')
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\user\Desktop\DevOps_Project\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\user\Desktop\DevOps_Project\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\user\Desktop\DevOps_Project\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\user\Desktop\DevOps_Project\tests\UserModelTest.php(10): CodeIgniter\BaseModel->findAll()
#6 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testFindAllUsers()
#7 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#8 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#9 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#10 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#11 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#12 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#13 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#14 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#15 C:\Users\user\Desktop\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\user\\D...')
#16 {main}
ERROR - 2025-05-01 16:32:09 --> Error connecting to the database: mysqli_sql_exception: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\user\Desktop\DevOps_Project\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\Users\user\Desktop\DevOps_Project\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'devops_tp', 3306, '', 0)
#1 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\Users\user\Desktop\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\user\Desktop\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\user\Desktop\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\Users\user\Desktop\DevOps_Project\tests\UserModelTest.php(17): CodeIgniter\Model->insert(Array)
#8 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testInsertUser()
#9 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#12 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#14 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#15 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#16 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#17 C:\Users\user\Desktop\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\user\\D...')
#18 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\user\Desktop\DevOps_Project\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\Users\user\Desktop\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\Users\user\Desktop\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#5 C:\Users\user\Desktop\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\Users\user\Desktop\DevOps_Project\tests\UserModelTest.php(17): CodeIgniter\Model->insert(Array)
#7 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testInsertUser()
#8 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#9 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#11 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#13 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#14 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#15 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#16 C:\Users\user\Desktop\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\user\\D...')
#17 {main}
ERROR - 2025-05-01 14:32:14 --> Error connecting to the database: mysqli_sql_exception: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\user\Desktop\DevOps_Project\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\Users\user\Desktop\DevOps_Project\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'devops_tp', 3306, '', 0)
#1 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\user\Desktop\DevOps_Project\system\Test\DatabaseTestTrait.php(83): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\user\Desktop\DevOps_Project\system\Test\DatabaseTestTrait.php(59): ExampleDatabaseTest->loadDependencies()
#4 C:\Users\user\Desktop\DevOps_Project\system\Test\CIUnitTestCase.php(251): ExampleDatabaseTest->setUpDatabase()
#5 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(2437): CodeIgniter\Test\CIUnitTestCase->setUp()
#6 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(2340): PHPUnit\Framework\TestCase->invokeHookMethods(Object(PHPUnit\Runner\HookMethodCollection), Object(PHPUnit\Event\DispatchingEmitter), 'beforeTestMetho...', 'beforeTestMetho...', 'beforeTestMetho...')
#7 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(506): PHPUnit\Framework\TestCase->invokeBeforeTestHookMethods(Array, Object(PHPUnit\Event\DispatchingEmitter))
#8 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#9 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(ExampleDatabaseTest))
#10 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#11 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#12 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#13 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#14 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#15 C:\Users\user\Desktop\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\user\\D...')
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\user\Desktop\DevOps_Project\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\user\Desktop\DevOps_Project\system\Test\DatabaseTestTrait.php(83): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\user\Desktop\DevOps_Project\system\Test\DatabaseTestTrait.php(59): ExampleDatabaseTest->loadDependencies()
#3 C:\Users\user\Desktop\DevOps_Project\system\Test\CIUnitTestCase.php(251): ExampleDatabaseTest->setUpDatabase()
#4 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(2437): CodeIgniter\Test\CIUnitTestCase->setUp()
#5 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(2340): PHPUnit\Framework\TestCase->invokeHookMethods(Object(PHPUnit\Runner\HookMethodCollection), Object(PHPUnit\Event\DispatchingEmitter), 'beforeTestMetho...', 'beforeTestMetho...', 'beforeTestMetho...')
#6 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(506): PHPUnit\Framework\TestCase->invokeBeforeTestHookMethods(Array, Object(PHPUnit\Event\DispatchingEmitter))
#7 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#8 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(ExampleDatabaseTest))
#9 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#10 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#11 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#12 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#13 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#14 C:\Users\user\Desktop\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\user\\D...')
#15 {main}
ERROR - 2025-05-01 14:32:19 --> Error connecting to the database: mysqli_sql_exception: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\user\Desktop\DevOps_Project\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\Users\user\Desktop\DevOps_Project\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'devops_tp', 3306, '', 0)
#1 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\user\Desktop\DevOps_Project\system\Test\DatabaseTestTrait.php(83): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\user\Desktop\DevOps_Project\system\Test\DatabaseTestTrait.php(59): ExampleDatabaseTest->loadDependencies()
#4 C:\Users\user\Desktop\DevOps_Project\system\Test\CIUnitTestCase.php(251): ExampleDatabaseTest->setUpDatabase()
#5 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(2437): CodeIgniter\Test\CIUnitTestCase->setUp()
#6 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(2340): PHPUnit\Framework\TestCase->invokeHookMethods(Object(PHPUnit\Runner\HookMethodCollection), Object(PHPUnit\Event\DispatchingEmitter), 'beforeTestMetho...', 'beforeTestMetho...', 'beforeTestMetho...')
#7 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(506): PHPUnit\Framework\TestCase->invokeBeforeTestHookMethods(Array, Object(PHPUnit\Event\DispatchingEmitter))
#8 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#9 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(ExampleDatabaseTest))
#10 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#11 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#12 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#13 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#14 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#15 C:\Users\user\Desktop\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\user\\D...')
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\user\Desktop\DevOps_Project\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\Users\user\Desktop\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\user\Desktop\DevOps_Project\system\Test\DatabaseTestTrait.php(83): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\user\Desktop\DevOps_Project\system\Test\DatabaseTestTrait.php(59): ExampleDatabaseTest->loadDependencies()
#3 C:\Users\user\Desktop\DevOps_Project\system\Test\CIUnitTestCase.php(251): ExampleDatabaseTest->setUpDatabase()
#4 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(2437): CodeIgniter\Test\CIUnitTestCase->setUp()
#5 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(2340): PHPUnit\Framework\TestCase->invokeHookMethods(Object(PHPUnit\Runner\HookMethodCollection), Object(PHPUnit\Event\DispatchingEmitter), 'beforeTestMetho...', 'beforeTestMetho...', 'beforeTestMetho...')
#6 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(506): PHPUnit\Framework\TestCase->invokeBeforeTestHookMethods(Array, Object(PHPUnit\Event\DispatchingEmitter))
#7 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#8 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(ExampleDatabaseTest))
#9 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#10 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#11 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#12 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#13 C:\Users\user\Desktop\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#14 C:\Users\user\Desktop\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\user\\D...')
#15 {main}
